# -*- coding: utf-8 -*-
"""College Major ROI Analysis v2.1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17-fEzzOkRzfMlfHty9pqoZgpXuRfxF0B
"""

import sklearn as sk
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

#importing Libraries

from google.colab import drive
drive.mount('/content/drive')

#mounting in order to connect it to the file

file_path = '/content/drive/MyDrive/Nicks Analyzed Data Sets/college_major_roi.csv' #defining the path to the data set
df = pd.read_csv(file_path)

#college_major_roi_csv will be referred to "df" from now on

#Viewing the dataset, using this section to find values in each column

#print(df)
print(df['major_category'].unique())

#i have to rip through EVERY SINGLE FUCKING MAJOR IN THIS GOD FORSAKEN DATA SET
df['major'] = df['major'].replace('biology', '1')
df['major'] = df['major'].replace('marketing', '2')
df['major'] = df['major'].replace('electrical_engineering', '3')
df['major'] = df['major'].replace('business', '4')
df['major'] = df['major'].replace('economics', '5')
df['major'] = df['major'].replace('social_work', '6')
df['major'] = df['major'].replace('mechanical_engineering', '7')
df['major'] = df['major'].replace('finance', '8')
df['major'] = df['major'].replace('computer_engineering', '9')
df['major'] = df['major'].replace('education', '10')
df['major'] = df['major'].replace('chemical_engineering', '11')
df['major'] = df['major'].replace('communications', '12')
df['major'] = df['major'].replace('computer_science', '13')
df['major'] = df['major'].replace('nursing', '14')
df['major'] = df['major'].replace('criminal_justice', '15')
df['major'] = df['major'].replace('fine_arts', '16')
df['major'] = df['major'].replace('humanities', '17')
df['major'] = df['major'].replace('psychology', '18')
df['major'] = df['major'].replace('business_analytics', '19')

#at least regions aren't too big
df['region'] = df['region'].replace('south', '1')
df['region'] = df['region'].replace('northeast', '2')
df['region'] = df['region'].replace('midwest', '3')
df['region'] = df['region'].replace('west', '4')

#major catagories yahoo
df['major_category'] = df['major_category'].replace('STEM', '1')
df['major_category'] = df['major_category'].replace('business', '2')
df['major_category'] = df['major_category'].replace('social_science', '3')
df['major_category'] = df['major_category'].replace('education', '4')
df['major_category'] = df['major_category'].replace('health', '5')
df['major_category'] = df['major_category'].replace('arts', '6')
df['major_category'] = df['major_category'].replace('humanities', '7')

#institution tier
df['institution_tier'] = df['institution_tier'].replace('mid_tier', '1')
df['institution_tier'] = df['institution_tier'].replace('top_public', '2')
df['institution_tier'] = df['institution_tier'].replace('ivy_elite', '3')
df['institution_tier'] = df['institution_tier'].replace('regional', '4')
df['institution_tier'] = df['institution_tier'].replace('for_profit', '5')

columns_to_drop = ['grad_id']
df_noID = df.drop(columns=columns_to_drop)

correlation_matrix = df_noID.corr()

sb.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")

plt.title("Correlation Matrix Heatmap")
plt.show()

#when you run it you CANNOT see shit with the numbers
#but essentially all the financial stuff is correlated with one another heavily

#this plot removes all values of which debt = 0
from sklearn.linear_model import LinearRegression
df_filtered = df[df['debt_usd'] != 0]
X = df_filtered[['net_cost_usd']]
y = df_filtered['debt_usd']
sb.set(style="whitegrid")
plt.scatter(X,  y, color='blue', alpha=0.5)
plt.xlabel("Net Cost")
plt.ylabel("Debt")
plt.title("Net Cost vs Debt")

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

# Fit the linear model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict and evaluate
y_pred_test = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred_test)
r2 = r2_score(y_test, y_pred_test)
print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

# Plot prediction vs actual
plt.scatter(y_test, y_pred_test)
plt.xlabel("actual debt")
plt.ylabel("predicted debt")
plt.title("actual vs predicted debt")
plt.grid(True)
plt.show()

#I lwk just ripped this from one of previous projects
#i mean I guess you could predict it based off of debt
#the model does capture most of the varience (about 67% [67 ahaha] of the varience)
#however the MSE is pretty large

